---
title: "Review of Select Statistics Calculator"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Source link: [Select Statistics's sample size calculator](https://select-statistics.co.uk/calculators/sample-size-calculator-population-proportion/)


## 1. Summary

The *select-statistics* calculator calculates sample sizes to estimate population proportions. Input parameters that users need to supply are margin of error, confidence level, population size, and the expected sample proportion. 

Several pros of the *select-statistics* calculator: 

* The calculator provides clear scope of usage of the calculator. In its opening section, *select-statistics* explicitly stated that the calculator only applicable for questions that have two responses.

* It offers guidance on how to use the calculator, such as the values of common input parameters and dealing with multiple questions. 

* It includes *Alternative Scenarios* feature, where users can vary an input parameter (holding other input parameters constant) and observe changes in the calculated sample size. 

* It states the formula underlying its calculation.

* For users who are less familiar with statistics, the calculator provides a worked example and brief definitions of input parameters and the calculator's outputs.


Study type(s) this calculator would be suitable for:

* Point in time surveys to estimate a proportion

* Humanitarian surveys

* Comparative surveys

* Study to test hypotheses


## 2. Review Checklist

1. What are the sampling assumptions  made for the calculator? 
* Simple random sampling without replacement.
* The sample proportion, $p$, is assumed to be normally distributed.
* The population size, $N$, is large and sampling fraction, $n/N$ is negligible.
* The resulting sample size, $n$, is moderately large (i.e., $n \geq 50$) such that normal approximation to t distribution can be used for the critical value (i.e, $z_{\alpha/2}$). 


2. What measure of accuracy is used for sample size calculation?
* No mention of coefficient of variation.
* Other: margin of error, confidence level.


3. If it includes continuous variables how do they determine variance of estimates since a distribution needs to be known or assumptions made about the distribution?
* Not applicable because the calculator does not include continuous variables. 


4. Is the calculator calculation correct?
[????]

5. If clustering of sample units, is a design effect suggested? What about for double sampling for stratification?
* No mention of cluster.
* No mention of design effect.


6. Is probability proportional to size, stratification, double sampling?
* No mentioned of probability proportional to size, stratification, or double sampling.

7. Accuracy of continuous variable estimate as well as that of proportion?
* The calculator only deals with proportion.


8. How does calculator deal with effect of non-response bias on accuracy?
* No mention of non-response.


## 3. Limitations

* Does the calculator apply to stratified samplings too or only simple random sampling?

* It will helpful to explicitly states that the calculator is only valid in surveys where the sampling units are classified into the property of interests. The calculator does not apply to surveys where each unit consists of elements and these elements are classified into property of interests, such as in cluster sampling (Cochran, 1977).

* May not be the best option when surveying rare items -- if population proportion is expected to be small (e.g.,  $P \leq 10%$). 

## 4. Verification of the Select Statistics calculator calculation


## 5. References






